version: '3'

services:
  database:
    image: postgres:14.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hibernate
      POSTGRES_PASSWORD: hibernate
      POSTGRES_DB: hibernate_db